src/ClaimsAuth/DinkLabs.ClaimsAuth.Web/Controllers/PermissionsController.cs
using System.Web.Mvc;

namespace DinkLabs.ClaimsAuth.Web.Controllers
{
    public class PermissionsController : Controller
    {
        public ActionResult Global()
        {
            return View();
        }

        public ActionResult Group(string id)
        {
            return View();
        }
    }
}

src/ClaimsAuth/DinkLabs.ClaimsAuth.Web/Controllers/SecurityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DinkLabs.ClaimsAuth.Web.Models;

namespace DinkLabs.ClaimsAuth.Web.Controllers
{
    public class SecurityController : Controller
    {
        // GET: Security
        public ActionResult Index()
        {
            var db = new ApplicationDbContext();
            var users = db.Users.ToList();
            return View(users);
        }

        public ActionResult Permissions()
        {
            return View();
        }

        public ActionResult Groups()
        {
            return View();
        }
        public ActionResult Resources()
        {
            var db = new ApplicationDbContext();
            var resources = db.ApplicationResource.ToList();
            return View(resources);
        }
        public ActionResult Associations()
        {
            return View();
        }
    }
}

src/ClaimsAuth/DinkLabs.ClaimsAuth.Web/Views/Security/Associations.cshtml
@model dynamic

@{
    ViewBag.Title = "Group Associations";
}

<h2>@ViewBag.Title</h2>

src/ClaimsAuth/DinkLabs.ClaimsAuth.Web/Views/Security/Groups.cshtml
@model dynamic

@{
    ViewBag.Title = "User Groups";
}

<h2>@ViewBag.Title</h2>

src/ClaimsAuth/DinkLabs.ClaimsAuth.Web/Views/Security/Index.cshtml
@model List<DinkLabs.ClaimsAuth.Web.Models.ApplicationUser>

@{
    ViewBag.Title = "Users";
}

<h2>Users</h2>

<div class="well">
    <a href="@Url.Action("Register", "Account")" class="btn btn-default">Add New User</a>
    <a href="@Url.Action("Groups", "Security")" class="btn btn-primary">Manage User Groups</a> 
    <a href="@Url.Action("Global", "Permissions")" class="btn btn-primary">Manage Global Permissions</a>
    <hr />
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>e-Mail</th>
                <th>Confirmed?</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model)
            {
                <tr>
                    <td><a href="#!">@user.Id</a></td>
                    <td>@user.Email</td>
                    <td><input type="checkbox" @(user.EmailConfirmed ? "checked" : "") disabled="disabled" /></td>
                </tr>
            }
        </tbody>
    </table>
</div>

src/ClaimsAuth/DinkLabs.ClaimsAuth.Web/Views/Security/Permissions.cshtml
@model dynamic

@{
    ViewBag.Title = "Permissions"; 
}

<h2>Permissions</h2>

src/ClaimsAuth/DinkLabs.ClaimsAuth.Web/Views/Security/Resources.cshtml
@model List<DinkLabs.ClaimsAuth.Web.Models.ApplicationResource>

@{
    ViewBag.Title = "Application Resources";
}

<h2>Application Resources</h2>

<div class="well">
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Resource</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var res in Model)
            {
                <tr>
                    <td><a href="#!">@res.ID</a></td>
                    <td>@string.Format("[{0}|{4}] ==> {1}/{2}/{3}", res.IsApiAction.GetValueOrDefault() ? "API" : "MVC", res.Area, res.Controller, res.Action, res.IsGetAction.GetValueOrDefault() ? "GET" : "POST/OTHER")</td>
                    <td>@res.Description</td>
                </tr>
            }
        </tbody>
    </table>
</div>